<?php

namespace App\Blendx;
use Carbon\Carbon;

class Subscription extends Blender {
    public static function store_validator($route)
    {
        $validator =  parent::store_validator($route); // TODO: Change the autogenerated stub
        unset($validator['expiry_date']);
        return $validator;
    }

    public static function after_validator($validated, $route, $user = null)
    {
        $expiry_date = Carbon::today()->add('30 days')->format('Y-m-d');
        $validated['expiry_date'] = $expiry_date;
        return parent::after_validator($validated, $route, $user);
    }
}
